export { default as Home } from './Home/Home'
export { default as PostPage } from './PostPage/PostPage'
export { default as AddPost } from './AddPost/AddPost'
export { default as Registration } from './Registration/Registration'
export { default as Login } from './Login/Login'
