export { default as Home } from './Home/Home'
export { default as FullPost } from './FullPost/FullPost'
export { default as AddPost } from './AddPost/AddPost'
export { default as Registration } from './Registration/Registration'
export { default as Login } from './Login/Login'
